import Head from 'next/head'
import {StoryblokComponent, getStoryblokApi} from "@storyblok/react"



export default function Home({story}) {
  return (
    <div>
      <Head>
        <title>Note app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>{story.title}</h2>
        <StoryblokComponent blok={story.content} />

      </div>
    </div>
  )
}

export async function getStaticProps(){
  let slug = "home";

  let sbParams = {
    version: "draft",
    resolve_relations: ["note-highlights.title"]
  }

  const storyblokApi = getStoryblokApi()

  let {data} = await storyblokApi.get(`cdn/stories/${slug}`, sbParams)
  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false
    },
    revalidate: 3600, 
  }
}